name: benchmarks

on:
  workflow_dispatch:

jobs:
  deploy-runner:
    runs-on: [ubuntu-latest]
    steps:
      - uses: actions/checkout@v3

      - uses: iterative/setup-cml@v1

      - name: deploy
        env:
          repo_token: ${{ secrets.HAYSTACK_BOT_TOKEN }}
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_CI_ACCESS_KEY }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_CI_SECRET_ACCESS_KEY }}
          AWS_CML_SECURITY_GROUP: ${{ secrets.AWS_CML_SECURITY_GROUP }}
        run: |
          cml runner launch \
          --cloud aws \
          --cloud-region us-east-1 \
          --cloud-type=p3.2xlarge \
          --cloud-aws-security-group="$AWS_CML_SECURITY_GROUP" \
          --labels=cml-runner

  run-benchmark:
    needs: deploy-runner
    runs-on: [self-hosted, cml-runner]
    steps:
      - uses: actions/checkout@v3

      - name: cml_run
        env:
          repo_token: ${{ secrets.HAYSTACK_BOT_TOKEN }}
        run: |
          apt-get update -y
          apt-get install python3-dev -y
          pip install .[elasticsearch,faiss,milvus,weaviate,graphdb,ray,rest,ui,dev]
          cd test/benchmarks && python run.py --retriever_index --retriever_query --reader --ci --save_markdown
          {
            echo -en "## Benchmarks: Retriever Indexing\n"
            cat retriever_index_results.md
            echo -en "\n\n## Benchmarks: Retriever Querying\n"
            cat retriever_query_results.md
            echo -en "\n\n## Benchmarks: Reader\n"
            cat reader_results.md
          } >> report.md
          cml-send-comment report.md
